[package]
name = "clash"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
claude_settings = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
dirs = { workspace = true }
figment = { workspace = true }
mac-notification-sys = { workspace = true }
tracing = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
regex = { workspace = true }
serde_regex = { workspace = true }
tracing-subscriber = { workspace = true }

# Linux only
[target.'cfg(target_os = "linux")']
rustflags = []
