[package]
name = "clash"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
sysinfo = { workspace = true }
claude_settings = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
